### ISSUE TITLE
Ignore failed optionalDependencies during install

### ISSUE THREAD

**Issue by zkat** [zkat/cipm#3]
It just crashes right now.

Keep in mind that this isn't as simple as ignoring failures: Any dependencies of the optionalDep _which are not used by anything else_ need to be removed.

**Comment by boneskull** [comment]
if one were so inclined to fix this, where would one start?

**Comment by zkat** [comment]
@boneskull this one's a bit tricky/involved so I'd recommend joining https://package.community so we can have a conversation about it -- previously we were thinking of just making it so failed run scripts would just not throw errors if the given dep is optional, and leave all the failed deps in place (because cipm can probably do that fine). This version is probably relatively low effort to implement.

The more involved one, if that turns out to be a bad idea, involves understanding the tree better and knowing what to remove and when.
