### ISSUE TITLE
Does not honour `--ignore-scripts`

### ISSUE THREAD

**Issue by rmg** [zkat/cipm#7]
Passing `--ignore-scripts` seems to have no effect, or at least doesn't do what I would expect it to do: ignore `preinstall`/`install`/`postinstall` scripts of dependencies during installation.

I noticed there is at least code for accepting the parameter, but haven't looked further yet to see where it might be getting dropped.

I also haven't looked at #6 yet to see if the refactor inadvertently fixes this.

**Comment by mikesherov** [comment]
Yeah, just not implemented yet. Feel free to issue a PR or just wait a week or so :-)

**Comment by rmg** [comment]
I submitted #9 just before your comment ;-)

**Comment by zkat** [comment]
probably more on the side of "hold up", since the script-runner code is kinda the focus right now and there's no real telling _how_ we're going to do the actual disabling yet.

**Comment by rmg** [comment]
Ultimately what is needed is #4, and this flag was just the most obvious workaround to try.

I'm fine either way, just didn't want to leave the issue hanging without putting some effort behind it to :-)
